### ISSUE TITLE
Workaround deserialization errors in Node API

### ISSUE THREAD

**Issue by olix0r** [Arnavion/k8s-openapi#97] opened 2021-05-19 23:41 UTC
We recently noticed some unexpected deserialization errors when reading `core::v1::Node` values. It turns out that there's a [serialization bug in Kubernetes](https://github.com/kubernetes/kubernetes/issues/100802#issuecomment-844561253) that can cause the `names` field to be encoded as `null` when it should be encoded as `[]`.

I've created a branch with a small [workaround](
https://github.com/olix0r/k8s-openapi/commit/1ebdf7920b04982419506cf30c56f4a6c9e5ff60) and it looks like they [intend to implement a similar workaround](https://github.com/kubernetes-client/python/issues/895#issuecomment-844567240) in the Python client.

Is there any interest in picking up a workaround in this repo? If so, do you have any pointers about how best to go about this in a way that will be maintainable until a Kubernetes fix is broadly available? Until such time, it's virtually impossible to use the Node API reliably with this library.

**Comment by Arnavion** [comment] 2021-05-19 23:50
Duplicate of https://github.com/Arnavion/k8s-openapi/issues/93

**Closed by Arnavion** 2021-05-19 23:50 UTC

**Comment by olix0r** [comment] 2021-05-19 23:51
@Arnavion sorry for the noise! thanks for the fix :)
